smartupload.server.name=www.yishunqianming.com
smartupload.port=80
smartupload.disk.tmpdir=D:/home/usr_upload/tmp/
smartupload.disk.preciousdir=D:/home/usr_upload/smart/
smartupload.disk.zipdir=D:/home/usr_upload/zip/