smartupload.server.name=localhost
smartupload.port=2222
smartupload.disk.tmpdir=./home/usr_upload/smart-history/
smartupload.disk.preciousdir=./home/usr_upload/smart/
smartupload.disk.zipdir=./home/usr_upload/zip/