tencent.apiUrl=sms.tencentcloudapi.com
tencent.region=ap-guangzhou
tencent.appId=1401038359
tencent.secretId=${TENCENT_SECRETID}
tencent.secretkey=${TENCENT_SECRETKEY}
tencent.registTemplateId=2522888
tencent.modifyPhoneTemplateId=2522892